### PR TITLE
Support for custom auto type backend

### PR DESCRIPTION
**Pull request by t0fik**
Added support for `ydotool` as auto-type backend.

### CODE REVIEW

**Comment by ayushnix** [comment]
I'm sorry but I can't accept this PR. I did mention in the README that I won't support ydotool because it needs root access. You may be able to bypass this requirement with udev rules but I don't want to take on the added complexity. In addition, [starting a daemon](https://github.com/ayushnix/tessen/pull/10/files#diff-a9940e2f3ccc956ca93a818a6e399634544f70a82a3a5c7698c73333f74586d3R483) from tessen doesn't sound good to me either.

wtype has none of the complexity that ydotool has and doesn't require any action from the user. It also works well on Firefox and maybe on Chromium as well.

**Comment by ayushnix** [comment]
Is there any feature that is possible with ydotool and not possible with wtype that is relevant to tessen?

**Comment by t0fik** [comment]
From features, used by tessen, perspective, I do not see any difference., in general `ydotool` allows for mouse interactions, which `wtype` is lacking.
`ydotool` seems to do not have drawbacks of `wtype` due to creation of actual device.
In my case `wtype` was not able to auto-type into VMware Horizon window. I do not have such problems with `ydotool`, which is used `passmenu`.

It would be nice to have plausibility to configure backend which fits best to your needs.

**Comment by ayushnix** [comment]
> In my case wtype was not able to auto-type into VMware Horizon window

I was able to autotype on [this VMWare Horizon URL](https://vmc-horizon.vmware.com/portal/webclient/#/home) without issues. Are you talking about the native client? If yes, does the native client run on XWayland?

**Comment by t0fik** [comment]
Yes, I'm talking about native client (I'm forced to use it) and yes it's xwayland window.
This is one of the reasons, I've added this feature. By default `tessen` will use `wtype`, if user have issues with auto-type, there will be plausibility to switch to `ydotool`, with all the problems to solve to get `ydotool` working.

**Comment by ayushnix** [comment]
> Yes, I'm talking about native client (I'm forced to use it) and yes it's xwayland window.

Hmm, from what I can see on the [wtype issue tracker](https://github.com/atx/wtype/issues/1), autotyping should work on xwayland windows as well but I haven't tried it myself and I'm not using any applications running under xwayland so I can't test this.

Considering that `wtype` does aim to support xwayland windows, maybe wtype not working on the VMWare Horizon window is a bug? If yes, I'd prefer that it would be fixed upstream on `wtype`.

Again, I'm sorry but I'm reluctant to accept this PR for now. Not supporting `ydotool` was an explicit goal from the beginning and it was done for good reason. 

I can see 3 possible paths you can pursue if you want this issue solved:
- use your fork
- raise an issue on the wtype repository
- use rofi-pass for xwayland windows (assuming that rofi-pass works on xwayland)

**Comment by t0fik** [comment]
This issue also might also be related with `wtype` problems when using on SwayWM.

Could you tell me the reason why you said no to support `ydotool`? I'm curious. About `root` requirement I know. Something else?

**Comment by ayushnix** [comment]
> This issue also might also be related with wtype problems when using on SwayWM.

Which problems exactly?

I've been autotyping using wtype on Firefox and on my terminal and it works fine. The v0.3 of wtype doesn't work with Chromium based browsers but that might've been fixed with the latest git release. As far as XWayland windows go, from what I can see, wtype does aim to support autotyping on XWayland windows as well. If it's not working for some reason, perhaps an issue or PR should be raised on the wtype repository.

> Could you tell me the reason why you said no to support ydotool? I'm curious. About root requirement I know. Something else?

Yeah, compared to wtype which needs no special permissions or configuration, ydotool needs to access `/dev/uinput` which typically needs root access. If not, maybe the user needs to be a part of the input group or have specific udev rules. Either way, it increases security risk for the user. As you can see, it also increases complexity in the code of `tessen`.

Another reason is that I don't really use `ydotool` myself and I have plans to do so. Therefore, I won't be able to maintain code for something that I don't use. Now, if the code needed to support ydotool would've been trivial, I might've accepted it but it isn't.

**Comment by t0fik** [comment]
On my configuration typed text is cut when auto typing to xwayland window, it does not matters what program. I was testing different delay values, without success.

After I sent you last message, I was thinking about solution and I got an idea to do something similar to `dmenu` solution. To add only the option to change auto-type backend program. Script/binary will have to be compatible with `wtype` on call level, support same switches in the same way. No complexity added to `tessen` and user can swap binary if needed.

**Comment by ayushnix** [comment]
Sorry, I won't add support for using arbitrary autotype backends in tessen. The original point about `ydotool` still stands. I won't support using something which needs root access to input when `wtype` works. If autotyping doesn't work on xwayland windows, you can use copy-paste instead.

**Pull request closed without merging**
