### PR TITLE
Invoke bash with env

### PR DESCRIPTION
**Pull request by svrana**
/bin/bash not available on all distrubutions- NixOS in my case.

### CODE REVIEW

**Comment by ayushnix** [comment]
Hmm, I lean towards using `/bin/bash` by default since that is what almost all Linux distributions use. If NixOS tries to be stateless and not have `/bin/bash`, maybe it's better to create a patch for it instead of changing the default shebang? The Makefile can probably be changed to use that patch and change the shebang during installation if needed.

**Comment by svrana** [comment]
Yes, it's very common to have bash in /bin, but even more common to ship with either gnu or bsd coreutils.

Go check out the code for pass or rofi-pass and you will see that env is preferred. Doing it this way also simplifies testing against different bash versions which may be useful to you down the road.

**Comment by ayushnix** [comment]
Closing as explained [here](https://github.com/ayushnix/tessen/pull/16#issuecomment-1038148775). This change will be incorporated as an optional patch in the next release.

**Comment by ayushnix** [comment]
fixed in [v2.0.0](https://github.com/ayushnix/tessen/blob/v2.0.0/CHANGELOG.md#200---2022-02-19).

**Pull request closed without merging**
